server:
  port: 9000

spring:
  application:
    name: authorization-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://authorization-server:9000

logging:
  level:
    com.ecommerce.authserver: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"