server:
  port: 8082

spring:
  application:
    name: analytics-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/analyticsdb}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

rabbitmq:
  exchange:
    order: order.exchange
  queue:
    analytics-order-created: analytics.order.created.queue
    analytics-status-changed: analytics.order.status.changed.queue
  routing-key:
    order-created: order.created
    order-status-changed: order.status.changed

logging:
  level:
    com.ecommerce.analytics: INFO
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"